# Generated by Django 5.1.6 on 2025-05-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_course_student_date_of_birth_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(default='ENG101', max_length=20),
        ),
    ]
